# Generated by Django 3.2 on 2021-04-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(default='url', max_length=150),
            preserve_default=False,
        ),
    ]
