# Generated by Django 3.2 on 2021-04-21 05:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210420_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='datetime',
        ),
        migrations.AddField(
            model_name='like',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 21, 5, 53, 58, 927732, tzinfo=utc)),
        ),
    ]
